SELECT
  COALESCE(SHOWING_TYPES.NAME, 'ALL') AS SHOWING_TYPE,
  round(sum(NETTO_PRICE), 2)          AS NETTO,
  round(sum(BRUTTO_PRICE), 2)         AS BRUTTO,
  count(*)                            AS COUNT
FROM SALES
  JOIN SHOWINGS ON SHOWINGS.ID = SALES.SHOWING_ID
  JOIN SHOWING_TYPES ON SHOWINGS.TYPE_ID = SHOWING_TYPES.ID
GROUP BY ROLLUP (SHOWING_TYPES.NAME)