-------------------------
-- ROW NUMBER
-------------------------

SELECT
  CATEGORY,
  MOVIE,
  TICKET_COUNT,
  BRUTTO_VALUE
FROM (
  SELECT
    MOVIES_CATEGORY.NAME AS CATEGORY,
    MOVIES.NAME AS MOVIE,
    SUM(SALES.BRUTTO_PRICE) AS BRUTTO_VALUE,
    SUM(SALES.TICKET_COUNT) AS TICKET_COUNT,
    ROW_NUMBER() OVER (PARTITION BY MOVIES_CATEGORY.NAME ORDER BY SUM(SALES.TICKET_COUNT) DESC ) ROW_NUMBER
  FROM SALES
    JOIN SHOWINGS ON SALES.SHOWING_ID = SHOWINGS.ID
    JOIN MOVIES ON SHOWINGS.MOVIE_ID = MOVIES.ID
    JOIN MOVIES_CATEGORY ON MOVIES.CATEGORY_ID = MOVIES_CATEGORY.ID
    JOIN CINEMAS ON SALES.CINEMA_ID = CINEMAS.ID
    JOIN CITIES ON CINEMAS.CITY_ID = CITIES.ID
    JOIN STATES ON CITIES.STATE_ID = STATES.ID
  GROUP BY GROUPING SETS ((MOVIES_CATEGORY.NAME, MOVIES.NAME))
  ORDER BY CATEGORY, TICKET_COUNT DESC
) WHERE ROW_NUMBER <= 5

