SELECT
  NVL(SHOWING_TYPES.NAME, 'ALL') AS TYPE,
  NVL(MOVIES_CATEGORY.NAME, 'ALL') AS CATEGORY,
  COUNT(*) AS COUNT,
  ROUND(SUM(SALES.BRUTTO_PRICE), 2) AS BRUTTO_VALUE
FROM SALES
  JOIN SHOWINGS ON SALES.SHOWING_ID = SHOWINGS.ID
  JOIN MOVIES ON SHOWINGS.MOVIE_ID = MOVIES.ID
  JOIN MOVIES_CATEGORY ON MOVIES.CATEGORY_ID = MOVIES_CATEGORY.ID
  JOIN SHOWING_TYPES ON SHOWINGS.TYPE_ID = SHOWING_TYPES.ID
GROUP BY CUBE(SHOWING_TYPES.NAME, MOVIES_CATEGORY.NAME)
ORDER BY COUNT DESC
