SELECT
  STATES.NAME AS STATE,
  NVL(MOVIES_CATEGORY.NAME, 'ALL') AS CATEGORY,
  COUNT(*) AS COUNT,
  SUM(SALES.BRUTTO_PRICE) AS BRUTTO
FROM SALES
  JOIN CINEMAS ON SALES.CINEMA_ID = CINEMAS.ID
  JOIN CITIES ON CINEMAS.CITY_ID = CITIES.ID
  JOIN STATES ON CITIES.STATE_ID = STATES.ID
  JOIN SHOWINGS ON SALES.SHOWING_ID = SHOWINGS.ID
  JOIN MOVIES ON SHOWINGS.MOVIE_ID = MOVIES.ID
  JOIN MOVIES_CATEGORY ON MOVIES.CATEGORY_ID = MOVIES_CATEGORY.ID
GROUP BY GROUPING SETS ((STATES.NAME, MOVIES_CATEGORY.NAME), STATES.NAME)
ORDER BY COUNT DESC