SELECT
  CINEMAS.NAME                                     AS CINEMA,
  MOVIES_CATEGORY.NAME                             AS MOVIE_CATEGORY,
  count(*)                                         AS COUNT,
  SUM(count(*)) OVER (PARTITION BY (CINEMAS.NAME)) AS COUNT_IN_CINEMA,
  ROUND(100 * (
    count(*) / SUM(count(*)) OVER (PARTITION BY (CINEMAS.NAME))
  ), 2) AS MOVIE_CATEGORY_PERCENT
FROM SALES
  JOIN CINEMAS ON SALES.CINEMA_ID = CINEMAS.ID
  JOIN SHOWINGS ON SALES.SHOWING_ID = SHOWINGS.ID
  JOIN MOVIES ON SHOWINGS.MOVIE_ID = MOVIES.ID
  JOIN MOVIES_CATEGORY ON MOVIES.CATEGORY_ID = MOVIES_CATEGORY.ID
GROUP BY (CINEMAS.NAME, MOVIES_CATEGORY.NAME)
ORDER BY CINEMA, MOVIE_CATEGORY_PERCENT DESC