SELECT
  COALESCE(YEARS.NAME, 'ALL')         AS YEAR,
  COALESCE(MONTHS.NAME, 'ALL')        AS MONTH,
  round(sum(NETTO_PRICE), 2)          AS NETTO,
  round(sum(BRUTTO_PRICE), 2)         AS BRUTTO,
  round(sum(TICKET_COUNT), 2)         AS TICKET_COUNT,
  count(*)                            AS COUNT
FROM SALES
  JOIN CINEMAS ON SALES.CINEMA_ID = CINEMAS.ID
  JOIN DAYS ON SALES.DAY_ID = DAYS.ID
  JOIN MONTHS ON DAYS.MONTH_ID = MONTHS.ID
  JOIN YEARS ON MONTHS.YEAR_ID = YEARS.ID
GROUP BY ROLLUP (YEARS.NAME, MONTHS.NAME)