--------------------------
-- RUCHOME OKIENKO
-------------------------

SELECT
  YEAR,
  MONTH,
  BRUTTO_VALUE,
  SUM(BRUTTO_VALUE)
  OVER (PARTITION BY YEAR
    ORDER BY MONTH RANGE
  BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS BRUTTO_VALUE_SALDO
FROM (
  SELECT
    YEARS.NAME              AS YEAR,
    TO_NUMBER(MONTHS.NAME)  AS MONTH,
    SUM(SALES.BRUTTO_PRICE) AS BRUTTO_VALUE
  FROM SALES
    JOIN DAYS ON SALES.DAY_ID = DAYS.ID
    JOIN MONTHS ON DAYS.MONTH_ID = MONTHS.ID
    JOIN YEARS ON MONTHS.YEAR_ID = YEARS.ID
  GROUP BY (YEARS.NAME, MONTHS.NAME)
)
