SELECT
  COALESCE(CITIES.NAME, 'ALL') AS CITY,
  round(sum(NETTO_PRICE), 2)   AS NETTO,
  round(sum(BRUTTO_PRICE), 2)  AS BRUTTO,
  count(*)                     AS COUNT
FROM SALES
  JOIN CINEMAS ON SALES.CINEMA_ID = CINEMAS.ID
  JOIN CITIES ON CINEMAS.CITY_ID = CITIES.ID
GROUP BY ROLLUP (CITIES.NAME)